name: Github Actions Base Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs: 
  Base-Actions:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Action test 1"
      - run: echo "Action test 2"